config/routes.rb
Rails.application.routes.draw do
  resources :subscribes
  devise_for :users
  resources :articles

  root "pages#main"
  match 'md_preview', to: 'pages#md_preview', via: [:post]
  match 'manifest', to: 'pages#manifest', via: [:get]
  match 'donate', to: 'pages#donate', via: [:get]
  match 'new_author', to: 'pages#new_author', via: [:get]

end

app/models/article.rb
class Article < ActiveRecord::Base
  default_scope -> { order('created_at DESC') }
  validates :title, presence: true
  validates :preview, presence: true
  validates :text, presence: true
  validates :author, presence: true
end

app/models/subscribe.rb
class Subscribe < ActiveRecord::Base
  validates :email, presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :new, :destroy]
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.paginate(:page => params[:page], :per_page => 3)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end

    @subscribes = Subscribe.all
    @subscribes.each do |subscribe|
      SubscribesMailer.new_article(subscribe.email).deliver_later
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :preview, :text, :author)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def main
    @articles = Article.limit(3)
  end

  def md_preview
    @text = params[:data]
    render "md_preview", layout: false
  end

  def manifest
  end

  def donate
  end

  def new_author
  end
end

app/controllers/subscribes_controller.rb
class SubscribesController < ApplicationController
  before_action :set_subscribe, only: [:show, :edit, :update, :destroy]

  # GET /subscribes
  # GET /subscribes.json
  def index
    @subscribes = Subscribe.all
  end

  # GET /subscribes/1
  # GET /subscribes/1.json
  def show
  end

  # GET /subscribes/new
  def new
    @subscribe = Subscribe.new
  end

  # GET /subscribes/1/edit
  def edit
  end

  # POST /subscribes
  # POST /subscribes.json
  def create
    @subscribe = Subscribe.new(subscribe_params)

    respond_to do |format|
      if @subscribe.save
        format.html { redirect_to @subscribe, notice: 'Subscribe was successfully created.' }
        format.json { render :show, status: :created, location: @subscribe }
      else
        format.html { render :new }
        format.json { render json: @subscribe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscribes/1
  # PATCH/PUT /subscribes/1.json
  def update
    respond_to do |format|
      if @subscribe.update(subscribe_params)
        format.html { redirect_to @subscribe, notice: 'Subscribe was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscribe }
      else
        format.html { render :edit }
        format.json { render json: @subscribe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscribes/1
  # DELETE /subscribes/1.json
  def destroy
    @subscribe.destroy
    respond_to do |format|
      format.html { redirect_to subscribes_url, notice: 'Subscribe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscribe
      @subscribe = Subscribe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscribe_params
      params.require(:subscribe).permit(:email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def markdown(text)
    renderer = Redcarpet::Render::HTML.new(hard_wrap: true, filter_html: true)
    options = {
        autolink: true,
        no_intra_emphasis: true,
        fenced_code_blocks: true,
        lax_html_blocks: true,
        strikethrough: true,
        superscript: true,
        space_after_headers: true
    }
    Redcarpet::Markdown.new(renderer, options).render(text).html_safe
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/subscribes_helper.rb
module SubscribesHelper
end

app/views/User/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/articles/_article.html.slim
article
  = link_to article_path(article)
    h1 #{article.title}
    = markdown(article.preview)
hr

app/views/articles/_form.html.slim
= form_for @article do |f|
  - if @article.errors.any?
    #error_explanation
      h2 = "#{pluralize(@article.errors.count, "error")} prohibited this article from being saved:"
      ul
        - @article.errors.full_messages.each do |message|
          li = message
  .field
    = f.label "Заголовок"
    br
    = f.text_field :title
  .field
    = f.label "Описание"
    br
    = f.text_area :preview
  .field
    = f.label "Текст"
    br
    = f.text_area :text
  .field
    = f.label "Подпись автора"
    br
    = f.text_field :author
  = f.submit "Создать статью"

app/views/articles/edit.html.slim
h1 Editing article

== render 'form'

= link_to 'Show', @article
'|
= link_to 'Back', articles_path

app/views/articles/index.html.slim
div#articles
  = render @articles
= will_paginate @articles

app/views/articles/index.js.erb
$('#articles').append('<%= escape_javascript render(@articles) %>');
$('.pagination').replaceWith('<%= escape_javascript will_paginate(@articles) %>');

app/views/articles/new.html.slim
h1.title Новая статья

== render 'form'

app/views/articles/show.html.slim
article.article

  // кнопки редактировать/удалить
  - if user_signed_in?
    div#edit
      = link_to edit_article_path(@article)
        = image_tag 'glyphicons-31-pencil.png'

      = link_to article_path(@article),data: {:confirm => 'Вы уверены, что хотите удалить статью?'}, method: 'delete'
        = image_tag 'glyphicons-208-remove-2.png'

  // статья
  h1 #{@article.title}
  div#preview
    = markdown(@article.preview)
  = markdown(@article.text)
  aside
    = @article.author

= image_tag 'border-botgray.png'

// комментарии
div id="disqus_thread"
script type="text/javascript"
    |var disqus_shortname = 'hitonplatona';
      (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
      })();
noscript
  |Please enable JavaScript to view the 
  a href="https://disqus.com/?ref_noscript" rel="nofollow" comments powered by Disqus.

// инициализация вк
script(language='javascript')
  |VK.init({apiId: 4900168, onlyWidgets: true});
  |VK.Widgets.Like("vk_like", {type: "button", height: 20});
// инициализация facebook
script
  |
    (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.3";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));

app/views/layouts/_header.html.slim
header
  a(href="/")
    = image_tag 'title.png'
  nav
    = image_tag 'border-top.png'
    ul
      li 
        = link_to 'все статьи', articles_path
      li
        = image_tag 'sep.png'
      li
        = link_to 'эйдос', 'http://vk.com/eidos_kfu'
      li
        = image_tag 'sep.png'
      li 
        = link_to 'манифест', manifest_path
      li
        = image_tag 'sep.png'
      li 
        = link_to 'стать автором', new_author_path
    = image_tag 'border-bot.png'

app/views/layouts/application.html.slim
doctype html
head
  title Хитон Платона
  meta(charset='utf-8')
  script type="text/javascript" src="//vk.com/js/api/openapi.js?116"
body
  section.wrapper
    = render 'layouts/header.html.slim'

    section
      = yield

    - if request.original_fullpath == '/'
      footer
        h2 Понравилось?
        = link_to donate_path
          h3
            |Поблагодари редакцию!
        div(id='share')
          a(href='http://www.facebook.com/sharer.php?u=#{request.original_url}&t=MY_TITLE&src=sp"' target="_blank")
            = image_tag 'fb.png'
          a(href='http://vk.com/share.php?url=#{request.original_url}' target="_blank")
            = image_tag 'vk.png'
    - else
      footer.article
        a(href='http://www.facebook.com/sharer.php?u=#{request.original_url}&t=MY_TITLE&src=sp"' target="_blank")
          = image_tag 'fbmin.png'
        a(href='http://vk.com/share.php?url=#{request.original_url}' target="_blank")
          = image_tag 'vkmin.png'
        = link_to donate_path, id: 'donate'
          |Поддержи проект

  a href="https://metrika.yandex.ru/stat/?id=30087979&amp;from=informer" target="_blank" rel="nofollow"
  img src="//bs.yandex.ru/informer/30087979/3_1_FFFFFFFF_EFEFEFFF_0_pageviews" style="width:88px; height:31px; border:0;" alt="Яндекс.Метрика" title="Яндекс.Метрика: данные за сегодня (просмотры, визиты и уникальные посетители)" onclick="try{Ya.Metrika.informer({i:this,id:30087979,lang:'ru'});return false}catch(e){}"

  script type="text/javascript"
    |
      (function (d, w, c) {
          (w[c] = w[c] || []).push(function() {
              try {
                  w.yaCounter30087979 = new Ya.Metrika({id:30087979,
                          trackLinks:true});
              } catch(e) { }
          });

          var n = d.getElementsByTagName("script")[0],
              s = d.createElement("script"),
              f = function () { n.parentNode.insertBefore(s, n); };
          s.type = "text/javascript";
          s.async = true;
          s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

          if (w.opera == "[object Opera]") {
              d.addEventListener("DOMContentLoaded", f, false);
          } else { f(); }
      })(document, window, "yandex_metrika_callbacks");
 
  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true 
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

app/views/pages/donate.html.slim
article.article
  p 
    |Если вам понравился наш журнал, если вы ощущаете нехватку философских изданий, если вы хотели бы, чтобы мы развивались и продолжали радовать вас интересными материалами, то вы всегда можете поддержать нашу редакцию:
  br
  br
  iframe frameborder="0" allowtransparency="true" scrolling="no" src="https://money.yandex.ru/embed/shop.xml?account=410013100413762&quickpay=shop&payment-type-choice=on&writer=buyer&targets-hint=&default-sum=350&button-text=03&fio=on&successURL=http%3A%2F%2Fphilochiton.com" width="450" height="194" style="margin-left: 150px;"

app/views/pages/main.html.slim
= render @articles

app/views/pages/manifest.html.slim
article.article
  p
   |Призрак бродит по Университету — призрак Платона. 
    Многие консервативные силы объединились для священной травли этого призрака.
    Но где же то студенческое объединение, которое бы защитило Платона? Сшило для него Хитон, чтобы Великий вновь обрел плоть?
  p
    |Да! Пора уже студентам-философам нашего университета перед всем миром открыто изложить свои взгляды, свои цели, свои стремления и сказкам о призраке противопоставить хитон смыслов — студенческое издание.     

  p
    |Да! Мы намерены воспеть любовь к философии, привычку к энергии и бесстрашию.
      Мысль, спор и ирония будут основными составляющими наших текстов.
      До сих пор студенческие издания восхваляли задумчивую неподвижность, экстаз и сон. Мы намерены воспеть действие, лихорадочную бессонницу, бег гонщика, прыжок в дальние дали. Мы будем воспевать студенчество, возбужденное работой; мы будем воспевать многоцветные, многозвучные, многозначные диспуты на кухнях общежитий и в коридорах Университета. 
  p
    |Да! Мы дадим слово ангелоголовым смельчакам, которые разглядели древних богов, придумывая заголовок для своей курсовой работы.
  p
    |Да! Мы станем выразителями духа новой казанской философии.
    |Слово тем, кто под самой луной обнажил свой разум перед небесами и увидел призрак того самого Платона, дрожащего на крышах высоких многоквартирных светил. 

  p
    |Мы дадим им слово.

  p
    |Да! Мы Хитон Платона!

app/views/pages/md_preview.html.slim
= markdown(@text)

app/views/pages/new_author.html.slim
article.article
  p 
    |Мы хотим дать потенциальным авторам возможность реализовать свою потребность заниматься философией в том жанре, который для них близок и органичен. Если вы способны писать проблемные, аналитические статьи (циклы статей) по проблемам социальной философии, языка, теории познания; о культуре, искусстве, истории, то вы тот, кто нам нужен!

  p
    |Какие существуют параметры текстов?

  p
    |Для нас важна, прежде всего, легкость изложения (без потери качества содержания). Кроме этого, хорошо, если текст отвечает следующим требованиям: неакадемичеость, ироничность, радикальность, философичность, логичность, образность. Материалы не должны содержать пространные размышления, упор делается на аргументированное изложение, доступное, но не поверхностное. Приоритетный жанр — эссе. Публикации должны подвигнуть читателя на последующее размышление, оставить после прочтения вопросы. Объем текста — до 11000 знаков с пробелами (если вы не умещаетесь в заданный объем, то всегда можно превратить статью в цикл статей).
  
  p
    |И да, у нас существует запрет на использование нецензурной лексики, а также на пропаганду любых политических и религиозных взглядов.

  p Чего нельзя допускать?

  p
    |Орфографических, пунктуационных и стилистических ошибок.
      Иллюстраций плохого качества, фотографий с указанием ссылок на источники.
      Копирования текстов из других источников. Даже те тексты, которые написаны на основе других источников, должны быть авторскими и индивидуальными.
      Нельзя использовать недостоверную, не проверенную информацию, способную ввести в заблуждение читательскую аудиторию.

  p Куда отправлять материалы?

  p 
    |На нашу почту - 
    a(href="mailto:philochiton@gmail.com") philochiton@gmail.com

app/views/subscribes/_form.html.slim
= form_for @subscribe do |f|
  - if @subscribe.errors.any?
    #error_explanation
      h2 = "#{pluralize(@subscribe.errors.count, "error")} prohibited this subscribe from being saved:"
      ul
        - @subscribe.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :email
    = f.text_field :email
  .actions = f.submit

app/views/subscribes/edit.html.slim
h1 Editing subscribe

== render 'form'

= link_to 'Show', @subscribe
'|
= link_to 'Back', subscribes_path

app/views/subscribes/index.html.slim
h1 Listing subscribes

table
  thead
    tr
      th Email
      th
      th
      th

  tbody
    - @subscribes.each do |subscribe|
      tr
        td = subscribe.email
        td = link_to 'Show', subscribe
        td = link_to 'Edit', edit_subscribe_path(subscribe)
        td = link_to 'Destroy', subscribe, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Subscribe', new_subscribe_path

app/views/subscribes/new.html.slim
h1 New subscribe

== render 'form'

= link_to 'Back', subscribes_path

app/views/subscribes/show.html.slim
p#notice = notice

p
  strong Email:
  = @subscribe.email

= link_to 'Edit', edit_subscribe_path(@subscribe)
'|
= link_to 'Back', subscribes_path